spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/counselink-db-test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql: true
      # console에 남기는 것보단 로그로 남기는 것이 좋다.
        format_sql: true
        # sql이 포맷형태로 예쁘게 나온다.
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 17525897d976bd829a19f5e15ff87293
            client-secret: f9AB1kIUia7VNnfL574aKPIbTuPGophA
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: 88GkLLrS9C9SpAekF89l
            client-secret: 8jU04aJkst
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 1054085135057-ut1loe5e7mo3pqqtqg29in0qaav1v026.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging.level:
  org.hibernate.SQL: debug