spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/counselink
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql: true
      # console에 남기는 것보단 로그로 남기는 것이 좋다.
        format_sql: true
        # sql이 포맷형태로 예쁘게 나온다.

logging.level:
  org.hibernate.SQL: debug